[[plugin.prepend_previewers]]
name = "*.nc"
run  = 'piper -- ncdump -h "$1"'

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
